name: Release

on:
  push:
    tags:
    - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Build and Publish Wheel and Bin
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
    steps:
    - name: ‚¨áÔ∏è Checkout Repository
      uses: actions/checkout@v6
    - name: üêç Install uv and Python
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.30"
        python-version: '3.14'
    - name: üõ†Ô∏è Build Wheel and Binary EXE
      run: |
        uv build --wheel
        uv sync --locked --group dev
        uv run pyinstaller -F src/openbq/cli.py -n openbq --distpath ./bin
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: üöÄ Upload Release Assets (Wheels/EXE)
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.whl
          bin/openbq
